version: "3.3"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokedex
    volumes:
      - mysql:/var/lib/mysql
  backend:
   build: ./backend
   image: yiisoftware/yii2-php:8.2-apache
   ports:
     - "8080:80"
   volumes:
     - ~/.composer-docker/cache:/root/.composer/cache:delegated
     - ./backend:/app:delegated
volumes:
  mysql: